version: "3"
services:
  mongodb:                          # This is our database service container
    image: mongo:latest               # We choose what database to connect with their default commands
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
    ports:
      - "27017:27017"
    env_file:                  # Choose our environment configuration used to start the container
      - .env
  spring-testcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:                # We are basically telling docker, before starting this java service please start 'db' service
      - mongodb
    links:                     # This enables the Network connection between the containers
      - mongodb
    ports:
      - '8080:8080'
    env_file:                  # Choose our environment configuration used to start the container
      - .env
